In [2]:
# =================================================================================================
# Raw data : This is Questionnaire data from NHANES 2003-2004
# Purpose : Creating unified raw CSV file from NHANES questionnaire CSV files.
# Specification : Each NHANES dataset has SEQN "Participant ID", which is the unique respondent ID.
# Files Used : ALQ_C.csv, BPQ_C.csv, DIQ_C.csv, HIQ_C.csv, HUQ_C.csv, SMQ_C.csv, SMQFAM_C.csv, WHQ_C.csv
# Data Dictionary : CDC NHANES 2003-2004 Questionnaire Data Dictionary
# Data Availability Matrix : Created in this notebook using SEQN presence flags
# Source Site : https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&CycleBeginYear=2003
# Developer Notes : The notebook was created for Windows desktop environment with Python3.
# File Creator : Neha Khairnar
# =================================================================================================
# 📦 Step 1: Imports
import pandas as pd
from pathlib import Path

# =================================================================================================
# 📂 Step 2: Paths below resolved for locally run datasets
# =================================================================================================

BASE_DIR = Path().resolve().parent
DATA_DIR = BASE_DIR / "data" / "2011_2012" / "Questionnnair"

alcohol_file = DATA_DIR / "ALQ_G_corrected.csv"
bp_chol_file = DATA_DIR / "BPQ_G_corrected.csv"
diabetes_file = DATA_DIR / "DIQ_G_corrected.csv"
insurance_file = DATA_DIR / "HIQ_G_corrected.csv"
access_file = DATA_DIR / "HUQ_G_corrected.csv"
smoking_file = DATA_DIR / "SMQ_G_corrected.csv"
household_smokers_file = DATA_DIR / "SMQFAM_G_corrected.csv"
weight_history_file = DATA_DIR / "WHQ_G_corrected.csv"
Housing_file = DATA_DIR / "HOQ_G_corrected.csv"
Occupation_file = DATA_DIR / "OCQ_G_corrected.csv"
medical_cndition_file = DATA_DIR / "MCQ_G_corrected.csv"
physical_file = DATA_DIR / "PAQ_G_corrected.csv"
#Osteo_file = DATA_DIR / "OSQ_G_corrected.csv"
Sleep_file = DATA_DIR / "SLQ_G_corrected.csv"

files = {
    "alcohol_ALQ_C": alcohol_file,
    "blood_pressure_cholesterol_BPQ_C": bp_chol_file,
    "diabetes_DIQ_C": diabetes_file,
    "health_insurance_HIQ_C": insurance_file,
    "hospital_access_HUQ_C": access_file,
    "smoking_SMQ_C": smoking_file,
    "household_smokers_SMQFAM_C": household_smokers_file,
    "weight_history_WHQ_C": weight_history_file,    
    "Housing_file_HOQ_C" : Housing_file,
    "Occupation_file_OCQ_C":Occupation_file,
    "medical_cndition_file_MCQ_C":medical_cndition_file,
    "physical_file" :physical_file,
    #"Osteo_file" : Osteo_file,
    "Sleep_file" : Sleep_file
}

# =================================================================================================
# 📥 Step 3: Load ALL Files
# =================================================================================================

dfs = {}
for name, path in files.items():
    df_temp = pd.read_csv(path, dtype=str,keep_default_na=False)
    df_temp.columns = df_temp.columns.str.upper()
    dfs[name] = df_temp

summary = []
for name, df_temp in dfs.items():
    summary.append({
        "file": name,
        "rows": df_temp.shape[0],
        "columns": df_temp.shape[1],
        "column_names": list(df_temp.columns)
    })

summary_df = pd.DataFrame(summary)
print("📊 NHANES Questionnaire File Structure Summary:\n")
display(summary_df[["file", "rows", "columns", "column_names"]])
for i, row in summary_df.iterrows():
    print("\n" + "="*80)
    print("FILE:", row["file"])
    print("COLUMNS:", len(row["column_names"]))
    print(row["column_names"])

# =================================================================================================
# 🔗 Step 5: Merge ALL columns using FULL OUTER JOIN on SEQN
# =================================================================================================

df = dfs["alcohol_ALQ_C"]
for name in [
    "blood_pressure_cholesterol_BPQ_C",
    "diabetes_DIQ_C",
    "health_insurance_HIQ_C",
    "hospital_access_HUQ_C",
    "smoking_SMQ_C",
    "household_smokers_SMQFAM_C",
    "weight_history_WHQ_C",    
    "Housing_file_HOQ_C",
    "Occupation_file_OCQ_C",
    "medical_cndition_file_MCQ_C",
    "physical_file",
    #"Osteo_file",
    "Sleep_file"
]:
    df = df.merge(
        dfs[name],
        on="SEQN",
        how="outer",
        suffixes=("", f"_{name}")
    )

# =================================================================================================
# 💾 Step 6: Save Final Output
# =================================================================================================
print("📋 Final Columns After Merge + Rename:")
print(df.columns.tolist())

print("\n📊 Final Shape:", df.shape)
display(df.head(20))


OUTPUT_DIR = BASE_DIR / "data" / "processed_v3" / "2011_2012"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "neighbourhood_nhanes_questionnaire_2011_2012_raw_corrected.csv"
df.to_csv(OUTPUT_PATH, index=False)
print("\n✅ Saved to:")
print(OUTPUT_PATH)

📊 NHANES Questionnaire File Structure Summary:

,file,rows,columns,column_names
0,alcohol_ALQ_C,5615,10,"[SEQN, ALQ101, ALQ110, ALQ120Q, ALQ120U, ALQ13..."
1,blood_pressure_cholesterol_BPQ_C,6175,15,"[SEQN, BPQ020, BPQ030, BPD035, BPQ040A, BPQ050..."
2,diabetes_DIQ_C,9364,53,"[SEQN, DIQ010, DID040, DIQ160, DIQ170, DIQ172,..."
3,health_insurance_HIQ_C,9756,17,"[SEQN, HIQ011, HIQ031A, HIQ031B, HIQ031C, HIQ0..."
4,hospital_access_HUQ_C,9756,10,"[SEQN, HUQ010, HUQ020, HUQ030, HUQ040, HUQ050,..."
5,smoking_SMQ_C,6790,30,"[SEQN, SMQ020, SMD030, SMQ040, SMQ050Q, SMQ050..."
6,household_smokers_SMQFAM_C,9756,5,"[SEQN, SMD410, SMD415, SMD415A, SMD430]"
7,weight_history_WHQ_C,6175,63,"[SEQN, WHD010, WHD020, WHQ030, WHQ040, WHD045,..."
8,Housing_file_HOQ_C,9756,3,"[SEQN, HOD050, HOQ065]"
9,Occupation_file_OCQ_C,6175,22,"[SEQN, OCD150, OCQ180, OCQ210, OCD231, OCD241,..."
10,medical_cndition_file_MCQ_C,9364,92,"[SEQN, MCQ010, MCQ025, MCQ035, MCQ040, MCQ050,..."
11,physical_file,9107,21,"[SEQN, PAQ706, PAQ605, PAQ610, PAD615, PAQ620,..."
12,Sleep_file,6175,4,"[SEQN, SLD010H, SLQ050, SLQ060]"

================================================================================
FILE: alcohol_ALQ_C
COLUMNS: 10
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ141Q', 'ALQ141U', 'ALQ151', 'ALQ155']

================================================================================
FILE: blood_pressure_cholesterol_BPQ_C
COLUMNS: 15
['SEQN', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ057', 'BPQ056', 'BPD058', 'BPQ059', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D']

================================================================================
FILE: diabetes_DIQ_C
COLUMNS: 53
['SEQN', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080']

================================================================================
FILE: health_insurance_HIQ_C
COLUMNS: 17
['SEQN', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210']

================================================================================
FILE: hospital_access_HUQ_C
COLUMNS: 10
['SEQN', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ040', 'HUQ050', 'HUQ060', 'HUQ071', 'HUD080', 'HUQ090']

================================================================================
FILE: smoking_SMQ_C
COLUMNS: 30
['SEQN', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ077', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ660', 'SMQ664M', 'SMQ664C', 'SMQ664W', 'SMQ664B', 'SMQ664O', 'SMQ670', 'SMAQUEX2']

================================================================================
FILE: household_smokers_SMQFAM_C
COLUMNS: 5
['SEQN', 'SMD410', 'SMD415', 'SMD415A', 'SMD430']

================================================================================
FILE: weight_history_WHQ_C
COLUMNS: 63
['SEQN', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD045', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080L', 'WHQ270', 'WHQ280A', 'WHQ280B', 'WHQ280C', 'WHQ280D', 'WHQ280E', 'WHQ090', 'WHD100A', 'WHD100B', 'WHD100C', 'WHD100D', 'WHD100E', 'WHD100F', 'WHD100G', 'WHD100H', 'WHD100I', 'WHD100J', 'WHD100K', 'WHD100M', 'WHD100N', 'WHD100O', 'WHD100P', 'WHD100Q', 'WHD100R', 'WHD100S', 'WHD100T', 'WHD100L', 'WHQ210', 'WHD220', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150']

================================================================================
FILE: Housing_file_HOQ_C
COLUMNS: 3
['SEQN', 'HOD050', 'HOQ065']

================================================================================
FILE: Occupation_file_OCQ_C
COLUMNS: 22
['SEQN', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCD270', 'OCQ275', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395', 'OCQ510', 'OCQ520', 'OCQ530', 'OCQ540', 'OCQ550', 'OCQ560', 'OCQ570', 'OCQ580']

================================================================================
FILE: medical_cndition_file_MCQ_C
COLUMNS: 92
['SEQN', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051', 'MCQ053', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ082', 'MCQ084', 'MCQ086', 'MCQ092', 'MCD093', 'MCQ140', 'MCQ149', 'MCQ160A', 'MCQ180A', 'MCQ195', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA', 'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD', 'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ365A', 'MCQ365B', 'MCQ365C', 'MCQ365D', 'MCQ370A', 'MCQ370B', 'MCQ370C', 'MCQ370D', 'MCQ380']

================================================================================
FILE: physical_file
COLUMNS: 21
['SEQN', 'PAQ706', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAQ710', 'PAQ715', 'PAAQUEX']

================================================================================
FILE: Sleep_file
COLUMNS: 4
['SEQN', 'SLD010H', 'SLQ050', 'SLQ060']
📋 Final Columns After Merge + Rename:
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ141Q', 'ALQ141U', 'ALQ151', 'ALQ155', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ057', 'BPQ056', 'BPD058', 'BPQ059', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ040', 'HUQ050', 'HUQ060', 'HUQ071', 'HUD080', 'HUQ090', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ077', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ660', 'SMQ664M', 'SMQ664C', 'SMQ664W', 'SMQ664B', 'SMQ664O', 'SMQ670', 'SMAQUEX2', 'SMD410', 'SMD415', 'SMD415A', 'SMD430', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD045', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080L', 'WHQ270', 'WHQ280A', 'WHQ280B', 'WHQ280C', 'WHQ280D', 'WHQ280E', 'WHQ090', 'WHD100A', 'WHD100B', 'WHD100C', 'WHD100D', 'WHD100E', 'WHD100F', 'WHD100G', 'WHD100H', 'WHD100I', 'WHD100J', 'WHD100K', 'WHD100M', 'WHD100N', 'WHD100O', 'WHD100P', 'WHD100Q', 'WHD100R', 'WHD100S', 'WHD100T', 'WHD100L', 'WHQ210', 'WHD220', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150', 'HOD050', 'HOQ065', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCD270', 'OCQ275', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395', 'OCQ510', 'OCQ520', 'OCQ530', 'OCQ540', 'OCQ550', 'OCQ560', 'OCQ570', 'OCQ580', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051', 'MCQ053', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ082', 'MCQ084', 'MCQ086', 'MCQ092', 'MCD093', 'MCQ140', 'MCQ149', 'MCQ160A', 'MCQ180A', 'MCQ195', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA', 'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD', 'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ365A', 'MCQ365B', 'MCQ365C', 'MCQ365D', 'MCQ370A', 'MCQ370B', 'MCQ370C', 'MCQ370D', 'MCQ380', 'PAQ706', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAQ710', 'PAQ715', 'PAAQUEX', 'SLD010H', 'SLQ050', 'SLQ060']

📊 Final Shape: (9756, 333)

,SEQN,ALQ101,ALQ110,ALQ120Q,ALQ120U,ALQ130,ALQ141Q,ALQ141U,ALQ151,ALQ155,...,PAQ665,PAQ670,PAD675,PAD680,PAQ710,PAQ715,PAAQUEX,SLD010H,SLQ050,SLQ060
0,62161,2,2,,,,,,,,...,2,,,300,3,3,1,8,2,2
1,62162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,0,8,1,NaN,NaN,NaN
2,62163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,,,720,2,3,2,NaN,NaN,NaN
3,62164,,,,,,,,,,...,1,1,45,300,2,8,1,8,1,2
4,62165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,2,25,600,5,2,2,NaN,NaN,NaN
5,62166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,2,0,1,NaN,NaN,NaN
6,62167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,62168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,3,2,1,NaN,NaN,NaN
8,62169,1,,1,2,2,1,3,2,,...,2,,,360,3,2,1,8,2,2
9,62170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,,,600,1,2,2,NaN,NaN,NaN
10,62171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,4,30,480,5,2,2,NaN,NaN,NaN
11,62172,1,,2,1,3,1,1,2,,...,2,,,720,5,5,1,8,2,2
12,62173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,1,8,1,NaN,NaN,NaN
13,62174,1,,0,,,,,2,,...,2,,,540,4,8,1,9,2,2
14,62175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,1,1,1,NaN,NaN,NaN
15,62176,1,,2,1,2,0,,2,,...,1,7,60,300,2,0,1,7,2,2
16,62177,,,,,,,,,,...,2,,,180,2,0,1,8,2,2
17,62178,2,2,,,,,,,,...,2,,,300,5,8,1,6,1,1
18,62179,2,1,0,,,,,2,,...,2,,,600,1,1,1,8,2,2
19,62180,1,,2,3,1,0,,1,666,...,2,,,540,2,1,1,7,1,2

✅ Saved to:
C:\Users\User\Desktop\Projects\Clinical_Neighbourhood_ML_Data_Predictor\Clinical_Neighbourhood_ML_Data_Predictor\data\processed_v3\2011_2012\neighbourhood_nhanes_questionnaire_2011_2012_raw_corrected.csv