In [1]:
# =================================================================================================
# Raw data : This is Questionnaire data from NHANES 2003-2004
# Purpose : Creating unified raw CSV file from NHANES questionnaire CSV files.
# Specification : Each NHANES dataset has SEQN "Participant ID", which is the unique respondent ID.
# Files Used : ALQ_C.csv, BPQ_C.csv, DIQ_C.csv, HIQ_C.csv, HUQ_C.csv, SMQ_C.csv, SMQFAM_C.csv, WHQ_C.csv
# Data Dictionary : CDC NHANES 2003-2004 Questionnaire Data Dictionary
# Data Availability Matrix : Created in this notebook using SEQN presence flags
# Source Site : https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&CycleBeginYear=2003
# Developer Notes : The notebook was created for Windows desktop environment with Python3.
# File Creator : Neha Khairnar
# =================================================================================================
# 📦 Step 1: Imports
import pandas as pd
from pathlib import Path

# =================================================================================================
# 📂 Step 2: Paths below resolved for locally run datasets
# =================================================================================================

BASE_DIR = Path().resolve().parent
DATA_DIR = BASE_DIR / "data" / "2017_2018" / "Questionnnair"

alcohol_file = DATA_DIR / "ALQ_J_corrected.csv"
bp_chol_file = DATA_DIR / "BPQ_J_corrected.csv"
diabetes_file = DATA_DIR / "DIQ_J_corrected.csv"
insurance_file = DATA_DIR / "HIQ_J_corrected.csv"
access_file = DATA_DIR / "HUQ_J_corrected.csv"
smoking_file = DATA_DIR / "SMQ_J_corrected.csv"
household_smokers_file = DATA_DIR / "SMQFAM_J_corrected.csv"
weight_history_file = DATA_DIR / "WHQ_J_corrected.csv"
Housing_file = DATA_DIR / "HOQ_J_corrected.csv"
Occupation_file = DATA_DIR / "OCQ_J_corrected.csv"
medical_cndition_file = DATA_DIR / "MCQ_J_corrected.csv"
physical_file = DATA_DIR / "PAQ_J_corrected.csv"
Osteo_file = DATA_DIR / "OSQ_J_corrected.csv"
Sleep_file = DATA_DIR / "SLQ_J_corrected.csv"

files = {
    "alcohol_ALQ_C": alcohol_file,
    "blood_pressure_cholesterol_BPQ_C": bp_chol_file,
    "diabetes_DIQ_C": diabetes_file,
    "health_insurance_HIQ_C": insurance_file,
    "hospital_access_HUQ_C": access_file,
    "smoking_SMQ_C": smoking_file,
    "household_smokers_SMQFAM_C": household_smokers_file,
    "weight_history_WHQ_C": weight_history_file,    
    "Housing_file_HOQ_C" : Housing_file,
    "Occupation_file_OCQ_C":Occupation_file,
    "medical_cndition_file_MCQ_C":medical_cndition_file,
    "physical_file" :physical_file,
    "Osteo_file" : Osteo_file,
    "Sleep_file" : Sleep_file
}

# =================================================================================================
# 📥 Step 3: Load ALL Files
# =================================================================================================

dfs = {}
for name, path in files.items():
    df_temp = pd.read_csv(path, dtype=str,keep_default_na=False)
    df_temp.columns = df_temp.columns.str.upper()
    dfs[name] = df_temp

summary = []
for name, df_temp in dfs.items():
    summary.append({
        "file": name,
        "rows": df_temp.shape[0],
        "columns": df_temp.shape[1],
        "column_names": list(df_temp.columns)
    })

summary_df = pd.DataFrame(summary)
print("📊 NHANES Questionnaire File Structure Summary:\n")
display(summary_df[["file", "rows", "columns", "column_names"]])
for i, row in summary_df.iterrows():
    print("\n" + "="*80)
    print("FILE:", row["file"])
    print("COLUMNS:", len(row["column_names"]))
    print(row["column_names"])

# =================================================================================================
# 🔗 Step 5: Merge ALL columns using FULL OUTER JOIN on SEQN
# =================================================================================================

df = dfs["alcohol_ALQ_C"]
for name in [
    "blood_pressure_cholesterol_BPQ_C",
    "diabetes_DIQ_C",
    "health_insurance_HIQ_C",
    "hospital_access_HUQ_C",
    "smoking_SMQ_C",
    "household_smokers_SMQFAM_C",
    "weight_history_WHQ_C",    
    "Housing_file_HOQ_C",
    "Occupation_file_OCQ_C",
    "medical_cndition_file_MCQ_C",
    "physical_file",
    "Osteo_file",
    "Sleep_file"
]:
    df = df.merge(
        dfs[name],
        on="SEQN",
        how="outer",
        suffixes=("", f"_{name}")
    )

# =================================================================================================
# 💾 Step 6: Save Final Output
# =================================================================================================
print("📋 Final Columns After Merge + Rename:")
print(df.columns.tolist())

print("\n📊 Final Shape:", df.shape)
display(df.head(20))


OUTPUT_DIR = BASE_DIR / "data" / "processed_v3" / "2017_2018"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "neighbourhood_nhanes_questionnaire_2017_2018_raw_corrected.csv"
df.to_csv(OUTPUT_PATH, index=False)
print("\n✅ Saved to:")
print(OUTPUT_PATH)

📊 NHANES Questionnaire File Structure Summary:

,file,rows,columns,column_names
0,alcohol_ALQ_C,5533,10,"[SEQN, ALQ111, ALQ121, ALQ130, ALQ142, ALQ270,..."
1,blood_pressure_cholesterol_BPQ_C,6161,11,"[SEQN, BPQ020, BPQ030, BPD035, BPQ040A, BPQ050..."
2,diabetes_DIQ_C,8897,54,"[SEQN, DIQ010, DID040, DIQ160, DIQ170, DIQ172,..."
3,health_insurance_HIQ_C,9254,16,"[SEQN, HIQ011, HIQ031A, HIQ031B, HIQ031C, HIQ0..."
4,hospital_access_HUQ_C,9254,10,"[SEQN, HUQ010, HUQ020, HUQ030, HUQ041, HUQ051,..."
5,smoking_SMQ_C,6724,37,"[SEQN, SMQ020, SMD030, SMQ040, SMQ050Q, SMQ050..."
6,household_smokers_SMQFAM_C,9254,4,"[SEQN, SMD460, SMD470, SMD480]"
7,weight_history_WHQ_C,6161,37,"[SEQN, WHD010, WHD020, WHQ030, WHQ040, WHD050,..."
8,Housing_file_HOQ_C,9254,3,"[SEQN, HOD050, HOQ065]"
9,Occupation_file_OCQ_C,6161,10,"[SEQN, OCD150, OCQ180, OCQ210, OCQ260, OCD270,..."
10,medical_cndition_file_MCQ_C,8897,76,"[SEQN, MCQ010, MCQ025, MCQ035, MCQ040, MCQ050,..."
11,physical_file,5856,17,"[SEQN, PAQ605, PAQ610, PAD615, PAQ620, PAQ625,..."
12,Osteo_file,3069,95,"[SEQN, OSQ010A, OSQ010B, OSQ010C, OSQ020A, OSQ..."
13,Sleep_file,6161,11,"[SEQN, SLQ300, SLQ310, SLD012, SLQ320, SLQ330,..."

================================================================================
FILE: alcohol_ALQ_C
COLUMNS: 10
['SEQN', 'ALQ111', 'ALQ121', 'ALQ130', 'ALQ142', 'ALQ270', 'ALQ280', 'ALQ290', 'ALQ151', 'ALQ170']

================================================================================
FILE: blood_pressure_cholesterol_BPQ_C
COLUMNS: 11
['SEQN', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D']

================================================================================
FILE: diabetes_DIQ_C
COLUMNS: 54
['SEQN', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080']

================================================================================
FILE: health_insurance_HIQ_C
COLUMNS: 16
['SEQN', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210']

================================================================================
FILE: hospital_access_HUQ_C
COLUMNS: 10
['SEQN', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ041', 'HUQ051', 'HUQ061', 'HUQ071', 'HUD080', 'HUQ090']

================================================================================
FILE: smoking_SMQ_C
COLUMNS: 37
['SEQN', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMQ890', 'SMQ895', 'SMQ900', 'SMQ905', 'SMQ910', 'SMQ915', 'SMAQUEX2']

================================================================================
FILE: household_smokers_SMQFAM_C
COLUMNS: 4
['SEQN', 'SMD460', 'SMD470', 'SMD480']

================================================================================
FILE: weight_history_WHQ_C
COLUMNS: 37
['SEQN', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080U', 'WHD080L', 'WHQ225', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150', 'WHQ190', 'WHQ200']

================================================================================
FILE: Housing_file_HOQ_C
COLUMNS: 3
['SEQN', 'HOD050', 'HOQ065']

================================================================================
FILE: Occupation_file_OCQ_C
COLUMNS: 10
['SEQN', 'OCD150', 'OCQ180', 'OCQ210', 'OCQ260', 'OCD270', 'OCQ670', 'OCQ380', 'OCD390G', 'OCD395']

================================================================================
FILE: medical_cndition_file_MCQ_C
COLUMNS: 76
['SEQN', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'AGQ030', 'MCQ053', 'MCQ080', 'MCQ092', 'MCD093', 'MCQ149', 'MCQ151', 'RHD018', 'MCQ160A', 'MCD180A', 'MCQ195', 'MCQ160N', 'MCD180N', 'MCQ160B', 'MCD180B', 'MCQ160C', 'MCD180C', 'MCQ160D', 'MCD180D', 'MCQ160E', 'MCD180E', 'MCQ160F', 'MCD180F', 'MCQ160M', 'MCQ170M', 'MCD180M', 'MCQ160G', 'MCD180G', 'MCQ160K', 'MCQ170K', 'MCD180K', 'MCQ160O', 'MCQ160L', 'MCQ170L', 'MCD180L', 'MCQ500', 'MCQ510A', 'MCQ510B', 'MCQ510C', 'MCQ510D', 'MCQ510E', 'MCQ510F', 'MCQ520', 'MCQ530', 'MCQ540', 'MCQ550', 'MCQ560', 'MCQ570', 'MCQ203', 'MCQ206', 'MCQ220', 'MCQ230A', 'MCD240A', 'MCQ230B', 'MCD240B', 'MCQ230C', 'MCD240C', 'MCQ230D', 'MCQ300B', 'MCQ300C', 'MCQ300A', 'MCQ366A', 'MCQ366B', 'MCQ366C', 'MCQ366D', 'MCQ371A', 'MCQ371B', 'MCQ371C', 'MCQ371D', 'OSQ230']

================================================================================
FILE: physical_file
COLUMNS: 17
['SEQN', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680']

================================================================================
FILE: Osteo_file
COLUMNS: 95
['SEQN', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD050BD', 'OSD030BE', 'OSQ040BE', 'OSD050BE', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSD050CC', 'OSD030CD', 'OSQ040CD', 'OSD050CD', 'OSD030CE', 'OSQ040CE', 'OSD050CE', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ100F', 'OSD110F', 'OSQ120F', 'OSQ090G', 'OSQ120G', 'OSQ090H', 'OSQ120H', 'OSQ090I', 'OSQ120I', 'OSQ090J', 'OSQ100J', 'OSD110J', 'OSQ120J', 'OSQ060', 'OSQ072', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220']

================================================================================
FILE: Sleep_file
COLUMNS: 11
['SEQN', 'SLQ300', 'SLQ310', 'SLD012', 'SLQ320', 'SLQ330', 'SLD013', 'SLQ030', 'SLQ040', 'SLQ050', 'SLQ120']
📋 Final Columns After Merge + Rename:
['SEQN', 'ALQ111', 'ALQ121', 'ALQ130', 'ALQ142', 'ALQ270', 'ALQ280', 'ALQ290', 'ALQ151', 'ALQ170', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ041', 'HUQ051', 'HUQ061', 'HUQ071', 'HUD080', 'HUQ090', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMQ890', 'SMQ895', 'SMQ900', 'SMQ905', 'SMQ910', 'SMQ915', 'SMAQUEX2', 'SMD460', 'SMD470', 'SMD480', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080U', 'WHD080L', 'WHQ225', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150', 'WHQ190', 'WHQ200', 'HOD050', 'HOQ065', 'OCD150', 'OCQ180', 'OCQ210', 'OCQ260', 'OCD270', 'OCQ670', 'OCQ380', 'OCD390G', 'OCD395', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'AGQ030', 'MCQ053', 'MCQ080', 'MCQ092', 'MCD093', 'MCQ149', 'MCQ151', 'RHD018', 'MCQ160A', 'MCD180A', 'MCQ195', 'MCQ160N', 'MCD180N', 'MCQ160B', 'MCD180B', 'MCQ160C', 'MCD180C', 'MCQ160D', 'MCD180D', 'MCQ160E', 'MCD180E', 'MCQ160F', 'MCD180F', 'MCQ160M', 'MCQ170M', 'MCD180M', 'MCQ160G', 'MCD180G', 'MCQ160K', 'MCQ170K', 'MCD180K', 'MCQ160O', 'MCQ160L', 'MCQ170L', 'MCD180L', 'MCQ500', 'MCQ510A', 'MCQ510B', 'MCQ510C', 'MCQ510D', 'MCQ510E', 'MCQ510F', 'MCQ520', 'MCQ530', 'MCQ540', 'MCQ550', 'MCQ560', 'MCQ570', 'MCQ203', 'MCQ206', 'MCQ220', 'MCQ230A', 'MCD240A', 'MCQ230B', 'MCD240B', 'MCQ230C', 'MCD240C', 'MCQ230D', 'MCQ300B', 'MCQ300C', 'MCQ300A', 'MCQ366A', 'MCQ366B', 'MCQ366C', 'MCQ366D', 'MCQ371A', 'MCQ371B', 'MCQ371C', 'MCQ371D', 'OSQ230', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD050BD', 'OSD030BE', 'OSQ040BE', 'OSD050BE', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSD050CC', 'OSD030CD', 'OSQ040CD', 'OSD050CD', 'OSD030CE', 'OSQ040CE', 'OSD050CE', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ100F', 'OSD110F', 'OSQ120F', 'OSQ090G', 'OSQ120G', 'OSQ090H', 'OSQ120H', 'OSQ090I', 'OSQ120I', 'OSQ090J', 'OSQ100J', 'OSD110J', 'OSQ120J', 'OSQ060', 'OSQ072', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220', 'SLQ300', 'SLQ310', 'SLD012', 'SLQ320', 'SLQ330', 'SLD013', 'SLQ030', 'SLQ040', 'SLQ050', 'SLQ120']

📊 Final Shape: (9254, 378)

,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ290,ALQ151,ALQ170,...,SLQ300,SLQ310,SLD012,SLQ320,SLQ330,SLD013,SLQ030,SLQ040,SLQ050,SLQ120
0,100000,1,8,2,0,,,,2,0,...,02:00,10:00,8.0,02:00,10:00,8.0,1,0,1,2
1,100001,1,4,6,4,0,7,10,2,4,...,02:00,10:00,8.0,02:00,10:00,8.0,3,2,1,3
2,100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100003,1,6,3,7,10,0,,2,2,...,00:00,08:00,8.0,01:00,11:00,10.0,0,0,2,2
4,100004,1,0,,,,,,2,,...,23:00,07:00,8.0,22:00,08:00,10.0,9,9,2,1
5,100005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,100006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,100007,1,0,,,,,,2,,...,20:00,02:00,6.0,21:30,06:00,8.5,0,0,2,2
8,100008,,,,,,,,,,...,22:00,05:00,7.0,23:00,07:00,8.0,3,2,2,2
9,100009,2,,,,,,,,,...,22:00,08:00,10.0,22:00,08:00,10.0,2,1,2,2
10,100010,2,,,,,,,,,...,22:00,08:00,10.0,22:00,08:00,10.0,3,3,2,1
11,100011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,100012,1,10,2,0,,,,2,0,...,22:00,06:30,8.5,22:00,08:00,10.0,3,0,2,0
13,100013,1,10,2,0,,,,2,,...,03:00,11:00,8.0,00:00,07:00,7.0,2,0,2,0
14,100014,1,6,2,0,,,,2,0,...,00:00,09:00,9.0,01:00,12:00,11.0,0,0,2,1
15,100015,1,10,12,10,10,10,10,2,1,...,02:00,07:00,5.0,04:00,14:00,10.0,3,0,2,0
16,100016,1,9,1,0,,,,2,0,...,00:00,08:00,8.0,01:00,09:00,8.0,3,0,2,2
17,100017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,100018,2,,,,,,,,,...,00:00,07:00,7.0,00:00,07:00,7.0,7,1,2,2
19,100019,1,0,,,,,,2,,...,00:00,06:30,6.5,00:00,08:00,8.0,1,0,1,0

✅ Saved to:
C:\Users\User\Desktop\Projects\Clinical_Neighbourhood_ML_Data_Predictor\Clinical_Neighbourhood_ML_Data_Predictor\data\processed_v3\2017_2018\neighbourhood_nhanes_questionnaire_2017_2018_raw_corrected.csv