In [2]:
# =================================================================================================
# Raw data : This is Questionnaire data from NHANES 2003-2004
# Purpose : Creating unified raw CSV file from NHANES questionnaire CSV files.
# Specification : Each NHANES dataset has SEQN "Participant ID", which is the unique respondent ID.
# Files Used : ALQ_C.csv, BPQ_C.csv, DIQ_C.csv, HIQ_C.csv, HUQ_C.csv, SMQ_C.csv, SMQFAM_C.csv, WHQ_C.csv
# Data Dictionary : CDC NHANES 2003-2004 Questionnaire Data Dictionary
# Data Availability Matrix : Created in this notebook using SEQN presence flags
# Source Site : https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&CycleBeginYear=2003
# Developer Notes : The notebook was created for Windows desktop environment with Python3.
# File Creator : Neha Khairnar
# =================================================================================================
# 📦 Step 1: Imports
import pandas as pd
from pathlib import Path

# =================================================================================================
# 📂 Step 2: Paths below resolved for locally run datasets
# =================================================================================================

BASE_DIR = Path().resolve().parent
DATA_DIR = BASE_DIR / "data" / "2013_2014" / "Questionnnair"

alcohol_file = DATA_DIR / "ALQ_H_corrected.csv"
bp_chol_file = DATA_DIR / "BPQ_H_corrected.csv"
diabetes_file = DATA_DIR / "DIQ_H_corrected.csv"
insurance_file = DATA_DIR / "HIQ_H_corrected.csv"
access_file = DATA_DIR / "HUQ_H_corrected.csv"
smoking_file = DATA_DIR / "SMQ_H_corrected.csv"
household_smokers_file = DATA_DIR / "SMQFAM_H_corrected.csv"
weight_history_file = DATA_DIR / "WHQ_H_corrected.csv"
Housing_file = DATA_DIR / "HOQ_H_corrected.csv"
Occupation_file = DATA_DIR / "OCQ_H_corrected.csv"
medical_cndition_file = DATA_DIR / "MCQ_H_corrected.csv"
physical_file = DATA_DIR / "PAQ_H_corrected.csv"
Osteo_file = DATA_DIR / "OSQ_H_corrected.csv"
Sleep_file = DATA_DIR / "SLQ_H_corrected.csv"

files = {
    "alcohol_ALQ_C": alcohol_file,
    "blood_pressure_cholesterol_BPQ_C": bp_chol_file,
    "diabetes_DIQ_C": diabetes_file,
    "health_insurance_HIQ_C": insurance_file,
    "hospital_access_HUQ_C": access_file,
    "smoking_SMQ_C": smoking_file,
    "household_smokers_SMQFAM_C": household_smokers_file,
    "weight_history_WHQ_C": weight_history_file,    
    "Housing_file_HOQ_C" : Housing_file,
    "Occupation_file_OCQ_C":Occupation_file,
    "medical_cndition_file_MCQ_C":medical_cndition_file,
    "physical_file" :physical_file,
    "Osteo_file" : Osteo_file,
    "Sleep_file" : Sleep_file
}

# =================================================================================================
# 📥 Step 3: Load ALL Files
# =================================================================================================

dfs = {}
for name, path in files.items():
    df_temp = pd.read_csv(path, dtype=str,keep_default_na=False)
    df_temp.columns = df_temp.columns.str.upper()
    dfs[name] = df_temp

summary = []
for name, df_temp in dfs.items():
    summary.append({
        "file": name,
        "rows": df_temp.shape[0],
        "columns": df_temp.shape[1],
        "column_names": list(df_temp.columns)
    })

summary_df = pd.DataFrame(summary)
print("📊 NHANES Questionnaire File Structure Summary:\n")
display(summary_df[["file", "rows", "columns", "column_names"]])
for i, row in summary_df.iterrows():
    print("\n" + "="*80)
    print("FILE:", row["file"])
    print("COLUMNS:", len(row["column_names"]))
    print(row["column_names"])

# =================================================================================================
# 🔗 Step 5: Merge ALL columns using FULL OUTER JOIN on SEQN
# =================================================================================================

df = dfs["alcohol_ALQ_C"]
for name in [
    "blood_pressure_cholesterol_BPQ_C",
    "diabetes_DIQ_C",
    "health_insurance_HIQ_C",
    "hospital_access_HUQ_C",
    "smoking_SMQ_C",
    "household_smokers_SMQFAM_C",
    "weight_history_WHQ_C",    
    "Housing_file_HOQ_C",
    "Occupation_file_OCQ_C",
    "medical_cndition_file_MCQ_C",
    "physical_file",
    "Osteo_file",
    "Sleep_file"
]:
    df = df.merge(
        dfs[name],
        on="SEQN",
        how="outer",
        suffixes=("", f"_{name}")
    )

# =================================================================================================
# 💾 Step 6: Save Final Output
# =================================================================================================
print("📋 Final Columns After Merge + Rename:")
print(df.columns.tolist())

print("\n📊 Final Shape:", df.shape)
display(df.head(20))


OUTPUT_DIR = BASE_DIR / "data" / "processed_v3" / "2013_2014"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "neighbourhood_nhanes_questionnaire_2013_2014_raw_corrected.csv"
df.to_csv(OUTPUT_PATH, index=False)
print("\n✅ Saved to:")
print(OUTPUT_PATH)

📊 NHANES Questionnaire File Structure Summary:

,file,rows,columns,column_names
0,alcohol_ALQ_C,5924,10,"[SEQN, ALQ101, ALQ110, ALQ120Q, ALQ120U, ALQ13..."
1,blood_pressure_cholesterol_BPQ_C,6464,14,"[SEQN, BPQ020, BPQ030, BPD035, BPQ040A, BPQ050..."
2,diabetes_DIQ_C,9770,54,"[SEQN, DIQ010, DID040, DIQ160, DIQ170, DIQ172,..."
3,health_insurance_HIQ_C,10175,17,"[SEQN, HIQ011, HIQ031A, HIQ031B, HIQ031C, HIQ0..."
4,hospital_access_HUQ_C,10175,10,"[SEQN, HUQ010, HUQ020, HUQ030, HUQ041, HUQ051,..."
5,smoking_SMQ_C,7168,32,"[SEQN, SMQ020, SMD030, SMQ040, SMQ050Q, SMQ050..."
6,household_smokers_SMQFAM_C,10175,4,"[SEQN, SMD460, SMD470, SMD480]"
7,weight_history_WHQ_C,6464,34,"[SEQN, WHD010, WHD020, WHQ030, WHQ040, WHD050,..."
8,Housing_file_HOQ_C,10175,3,"[SEQN, HOD050, HOQ065]"
9,Occupation_file_OCQ_C,6464,13,"[SEQN, OCD150, OCQ180, OCQ210, OCD231, OCD241,..."
10,medical_cndition_file_MCQ_C,9770,95,"[SEQN, MCQ010, MCQ025, MCQ035, MCQ040, MCQ050,..."
11,physical_file,9484,96,"[SEQN, PAQ605, PAQ610, PAD615, PAQ620, PAQ625,..."
12,Osteo_file,3815,91,"[SEQN, OSQ010A, OSQ010B, OSQ010C, OSQ020A, OSQ..."
13,Sleep_file,6464,4,"[SEQN, SLD010H, SLQ050, SLQ060]"

================================================================================
FILE: alcohol_ALQ_C
COLUMNS: 10
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ141Q', 'ALQ141U', 'ALQ151', 'ALQ160']

================================================================================
FILE: blood_pressure_cholesterol_BPQ_C
COLUMNS: 14
['SEQN', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ056', 'BPD058', 'BPQ059', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D']

================================================================================
FILE: diabetes_DIQ_C
COLUMNS: 54
['SEQN', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080']

================================================================================
FILE: health_insurance_HIQ_C
COLUMNS: 17
['SEQN', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210']

================================================================================
FILE: hospital_access_HUQ_C
COLUMNS: 10
['SEQN', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ041', 'HUQ051', 'HUQ061', 'HUQ071', 'HUD080', 'HUQ090']

================================================================================
FILE: smoking_SMQ_C
COLUMNS: 32
['SEQN', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMAQUEX2']

================================================================================
FILE: household_smokers_SMQFAM_C
COLUMNS: 4
['SEQN', 'SMD460', 'SMD470', 'SMD480']

================================================================================
FILE: weight_history_WHQ_C
COLUMNS: 34
['SEQN', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080U', 'WHD080L', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150']

================================================================================
FILE: Housing_file_HOQ_C
COLUMNS: 3
['SEQN', 'HOD050', 'HOQ065']

================================================================================
FILE: Occupation_file_OCQ_C
COLUMNS: 13
['SEQN', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCD270', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395']

================================================================================
FILE: medical_cndition_file_MCQ_C
COLUMNS: 95
['SEQN', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'AGQ030', 'MCQ053', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ082', 'MCQ084', 'MCQ086', 'MCQ092', 'MCD093', 'MCQ149', 'MCQ151', 'MCQ160A', 'MCQ180A', 'MCQ195', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ160O', 'MCQ203', 'MCQ206', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA', 'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD', 'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ365A', 'MCQ365B', 'MCQ365C', 'MCQ365D', 'MCQ370A', 'MCQ370B', 'MCQ370C', 'MCQ370D', 'MCQ380']

================================================================================
FILE: physical_file
COLUMNS: 96
['SEQN', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAQ706', 'PAQ710', 'PAQ715', 'PAQ722', 'PAQ724A', 'PAQ724B', 'PAQ724C', 'PAQ724D', 'PAQ724E', 'PAQ724F', 'PAQ724G', 'PAQ724H', 'PAQ724I', 'PAQ724J', 'PAQ724K', 'PAQ724L', 'PAQ724M', 'PAQ724N', 'PAQ724O', 'PAQ724P', 'PAQ724Q', 'PAQ724R', 'PAQ724S', 'PAQ724T', 'PAQ724U', 'PAQ724V', 'PAQ724W', 'PAQ724X', 'PAQ724Y', 'PAQ724Z', 'PAQ724AA', 'PAQ724AB', 'PAQ724AC', 'PAQ724AD', 'PAQ724AE', 'PAQ724AF', 'PAQ724CM', 'PAQ731', 'PAD733', 'PAQ677', 'PAQ678', 'PAQ740', 'PAQ742', 'PAQ744', 'PAQ746', 'PAQ748', 'PAQ755', 'PAQ759A', 'PAQ759B', 'PAQ759C', 'PAQ759D', 'PAQ759E', 'PAQ759F', 'PAQ759G', 'PAQ759H', 'PAQ759I', 'PAQ759J', 'PAQ759K', 'PAQ759L', 'PAQ759M', 'PAQ759N', 'PAQ759O', 'PAQ759P', 'PAQ759Q', 'PAQ759R', 'PAQ759S', 'PAQ759T', 'PAQ759U', 'PAQ759V', 'PAQ762', 'PAQ764', 'PAQ766', 'PAQ679', 'PAQ750', 'PAQ770', 'PAQ772A', 'PAQ772B', 'PAQ772C', 'PAAQUEX']

================================================================================
FILE: Osteo_file
COLUMNS: 91
['SEQN', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD050BD', 'OSD030BE', 'OSQ040BE', 'OSD030BF', 'OSQ040BF', 'OSD030BG', 'OSQ040BG', 'OSD030BH', 'OSQ040BH', 'OSD030BI', 'OSQ040BI', 'OSD030BJ', 'OSQ040BJ', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ120F', 'OSQ090G', 'OSQ100G', 'OSD110G', 'OSQ120G', 'OSQ090H', 'OSQ120H', 'OSQ060', 'OSQ072', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220']

================================================================================
FILE: Sleep_file
COLUMNS: 4
['SEQN', 'SLD010H', 'SLQ050', 'SLQ060']
📋 Final Columns After Merge + Rename:
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ141Q', 'ALQ141U', 'ALQ151', 'ALQ160', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ056', 'BPD058', 'BPQ059', 'BPQ080', 'BPQ060', 'BPQ070', 'BPQ090D', 'BPQ100D', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ041', 'HUQ051', 'HUQ061', 'HUQ071', 'HUD080', 'HUQ090', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMAQUEX2', 'SMD460', 'SMD470', 'SMD480', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHD080T', 'WHD080U', 'WHD080L', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150', 'HOD050', 'HOQ065', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCD270', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'AGQ030', 'MCQ053', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ082', 'MCQ084', 'MCQ086', 'MCQ092', 'MCD093', 'MCQ149', 'MCQ151', 'MCQ160A', 'MCQ180A', 'MCQ195', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ160O', 'MCQ203', 'MCQ206', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA', 'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD', 'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ365A', 'MCQ365B', 'MCQ365C', 'MCQ365D', 'MCQ370A', 'MCQ370B', 'MCQ370C', 'MCQ370D', 'MCQ380', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAQ706', 'PAQ710', 'PAQ715', 'PAQ722', 'PAQ724A', 'PAQ724B', 'PAQ724C', 'PAQ724D', 'PAQ724E', 'PAQ724F', 'PAQ724G', 'PAQ724H', 'PAQ724I', 'PAQ724J', 'PAQ724K', 'PAQ724L', 'PAQ724M', 'PAQ724N', 'PAQ724O', 'PAQ724P', 'PAQ724Q', 'PAQ724R', 'PAQ724S', 'PAQ724T', 'PAQ724U', 'PAQ724V', 'PAQ724W', 'PAQ724X', 'PAQ724Y', 'PAQ724Z', 'PAQ724AA', 'PAQ724AB', 'PAQ724AC', 'PAQ724AD', 'PAQ724AE', 'PAQ724AF', 'PAQ724CM', 'PAQ731', 'PAD733', 'PAQ677', 'PAQ678', 'PAQ740', 'PAQ742', 'PAQ744', 'PAQ746', 'PAQ748', 'PAQ755', 'PAQ759A', 'PAQ759B', 'PAQ759C', 'PAQ759D', 'PAQ759E', 'PAQ759F', 'PAQ759G', 'PAQ759H', 'PAQ759I', 'PAQ759J', 'PAQ759K', 'PAQ759L', 'PAQ759M', 'PAQ759N', 'PAQ759O', 'PAQ759P', 'PAQ759Q', 'PAQ759R', 'PAQ759S', 'PAQ759T', 'PAQ759U', 'PAQ759V', 'PAQ762', 'PAQ764', 'PAQ766', 'PAQ679', 'PAQ750', 'PAQ770', 'PAQ772A', 'PAQ772B', 'PAQ772C', 'PAAQUEX', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD050BD', 'OSD030BE', 'OSQ040BE', 'OSD030BF', 'OSQ040BF', 'OSD030BG', 'OSQ040BG', 'OSD030BH', 'OSQ040BH', 'OSD030BI', 'OSQ040BI', 'OSD030BJ', 'OSQ040BJ', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ120F', 'OSQ090G', 'OSQ100G', 'OSD110G', 'OSQ120G', 'OSQ090H', 'OSQ120H', 'OSQ060', 'OSQ072', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220', 'SLD010H', 'SLQ050', 'SLQ060']

📊 Final Shape: (10175, 464)

,SEQN,ALQ101,ALQ110,ALQ120Q,ALQ120U,ALQ130,ALQ141Q,ALQ141U,ALQ151,ALQ160,...,OSQ160B,OSQ170,OSQ180,OSQ190,OSQ200,OSQ210,OSQ220,SLD010H,SLQ050,SLQ060
0,73557,1,,1,3,1,0,,1,,...,,2,,,9,,,7,1,2
1,73558,1,,7,1,4,2,1,1,0,...,,2,,,2,,,9,2,2
2,73559,1,,0,,,,,2,,...,,2,,,2,,,8,2,2
3,73560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561,1,,0,,,,,2,,...,,2,,,2,,,9,2,2
5,73562,1,,5,3,1,0,,2,0,...,,1,999,1,2,,,5,2,1
6,73563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,73564,2,1,2,3,1,0,,2,,...,,2,,,2,,,9,2,1
8,73565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,2,,,2,,,7,2,2
9,73566,1,,1,1,1,0,,2,,...,,2,,,2,,,6,1,2
10,73567,1,,4,1,3,0,,2,,...,,2,,,2,,,7,2,2
11,73568,1,,2,1,2,1,3,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,2
12,73569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,73570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,73571,2,1,2,3,1,0,,2,,...,,2,,,2,,,6,1,2
15,73572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,73573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,73574,2,2,,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,2
18,73575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,73576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2,2

✅ Saved to:
C:\Users\User\Desktop\Projects\Clinical_Neighbourhood_ML_Data_Predictor\Clinical_Neighbourhood_ML_Data_Predictor\data\processed_v3\2013_2014\neighbourhood_nhanes_questionnaire_2013_2014_raw_corrected.csv