In [1]:
# =================================================================================================
# Raw data : This is Questionnaire data from NHANES 2003-2004
# Purpose : Creating unified raw CSV file from NHANES questionnaire CSV files.
# Specification : Each NHANES dataset has SEQN "Participant ID", which is the unique respondent ID.
# Files Used : ALQ_C.csv, BPQ_C.csv, DIQ_C.csv, HIQ_C.csv, HUQ_C.csv, SMQ_C.csv, SMQFAM_C.csv, WHQ_C.csv
# Data Dictionary : CDC NHANES 2003-2004 Questionnaire Data Dictionary
# Data Availability Matrix : Created in this notebook using SEQN presence flags
# Source Site : https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&CycleBeginYear=2003
# Developer Notes : The notebook was created for Windows desktop environment with Python3.
# File Creator : Neha Khairnar
# =================================================================================================
# 📦 Step 1: Imports
import pandas as pd
from pathlib import Path

# =================================================================================================
# 📂 Step 2: Paths below resolved for locally run datasets
# =================================================================================================

BASE_DIR = Path().resolve().parent
DATA_DIR = BASE_DIR / "data" / "2007_2008" / "Questionnnair"

alcohol_file = DATA_DIR / "ALQ_E_corrected.csv"
bp_chol_file = DATA_DIR / "BPQ_E_corrected.csv"
diabetes_file = DATA_DIR / "DIQ_E_corrected.csv"
insurance_file = DATA_DIR / "HIQ_E_corrected.csv"
access_file = DATA_DIR / "HUQ_E_corrected.csv"
smoking_file = DATA_DIR / "SMQ_E_corrected.csv"
household_smokers_file = DATA_DIR / "SMQFAM_E_corrected.csv"
weight_history_file = DATA_DIR / "WHQ_E_corrected.csv"
Housing_file = DATA_DIR / "HOQ_E_corrected.csv"
Occupation_file = DATA_DIR / "OCQ_E_corrected.csv"
medical_cndition_file = DATA_DIR / "MCQ_E_corrected.csv"
physical_file = DATA_DIR / "PAQ_E_corrected.csv"
Osteo_file = DATA_DIR / "OSQ_E_corrected.csv"
Sleep_file = DATA_DIR / "SLQ_E_corrected.csv"

files = {
    "alcohol_ALQ_C": alcohol_file,
    "blood_pressure_cholesterol_BPQ_C": bp_chol_file,
    "diabetes_DIQ_C": diabetes_file,
    "health_insurance_HIQ_C": insurance_file,
    "hospital_access_HUQ_C": access_file,
    "smoking_SMQ_C": smoking_file,
    "household_smokers_SMQFAM_C": household_smokers_file,
    "weight_history_WHQ_C": weight_history_file,    
    "Housing_file_HOQ_C" : Housing_file,
    "Occupation_file_OCQ_C":Occupation_file,
    "medical_cndition_file_MCQ_C":medical_cndition_file,
    "physical_file" :physical_file,
    "Osteo_file" : Osteo_file,
    "Sleep_file" : Sleep_file
}

# =================================================================================================
# 📥 Step 3: Load ALL Files
# =================================================================================================

dfs = {}
for name, path in files.items():
    df_temp = pd.read_csv(path, dtype=str,keep_default_na=False)
    df_temp.columns = df_temp.columns.str.upper()
    dfs[name] = df_temp

summary = []
for name, df_temp in dfs.items():
    summary.append({
        "file": name,
        "rows": df_temp.shape[0],
        "columns": df_temp.shape[1],
        "column_names": list(df_temp.columns)
    })

summary_df = pd.DataFrame(summary)
print("📊 NHANES Questionnaire File Structure Summary:\n")
display(summary_df[["file", "rows", "columns", "column_names"]])
for i, row in summary_df.iterrows():
    print("\n" + "="*80)
    print("FILE:", row["file"])
    print("COLUMNS:", len(row["column_names"]))
    print(row["column_names"])

# =================================================================================================
# 🔗 Step 5: Merge ALL columns using FULL OUTER JOIN on SEQN
# =================================================================================================

df = dfs["alcohol_ALQ_C"]
for name in [
    "blood_pressure_cholesterol_BPQ_C",
    "diabetes_DIQ_C",
    "health_insurance_HIQ_C",
    "hospital_access_HUQ_C",
    "smoking_SMQ_C",
    "household_smokers_SMQFAM_C",
    "weight_history_WHQ_C",    
    "Housing_file_HOQ_C",
    "Occupation_file_OCQ_C",
    "medical_cndition_file_MCQ_C",
    "physical_file",
    "Osteo_file",
    "Sleep_file"
]:
    df = df.merge(
        dfs[name],
        on="SEQN",
        how="outer",
        suffixes=("", f"_{name}")
    )

# =================================================================================================
# 💾 Step 6: Save Final Output
# =================================================================================================
print("📋 Final Columns After Merge + Rename:")
print(df.columns.tolist())

print("\n📊 Final Shape:", df.shape)
display(df.head(20))


OUTPUT_DIR = BASE_DIR / "data" / "processed_v3" / "2007_2008"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "neighbourhood_nhanes_questionnaire_2007_2008_raw_corrected.csv"
df.to_csv(OUTPUT_PATH, index=False)
print("\n✅ Saved to:")
print(OUTPUT_PATH)

📊 NHANES Questionnaire File Structure Summary:

,file,rows,columns,column_names
0,alcohol_ALQ_C,5707,9,"[SEQN, ALQ101, ALQ110, ALQ120Q, ALQ120U, ALQ13..."
1,blood_pressure_cholesterol_BPQ_C,6546,19,"[SEQN, BPQ020, BPQ030, BPD035, BPQ040A, BPQ050..."
2,diabetes_DIQ_C,9666,36,"[SEQN, DIQ010, DID040, DIQ220, DIQ160, DIQ170,..."
3,health_insurance_HIQ_C,10149,17,"[SEQN, HIQ011, HIQ031A, HIQ031B, HIQ031C, HIQ0..."
4,hospital_access_HUQ_C,10149,10,"[SEQN, HUQ010, HUQ020, HUQ030, HUQ040, HUQ050,..."
5,smoking_SMQ_C,7145,37,"[SEQN, SMQ020, SMD030, SMQ040, SMQ050Q, SMQ050..."
6,household_smokers_SMQFAM_C,10149,5,"[SEQN, SMD410, SMD415, SMD415A, SMD430]"
7,weight_history_WHQ_C,6546,58,"[SEQN, WHD010, WHD020, WHQ030, WHQ040, WHD045,..."
8,Housing_file_HOQ_C,10149,7,"[SEQN, HOQ040, HOD050, HOD060, HOQ065, HOQ070,..."
9,Occupation_file_OCQ_C,6546,24,"[SEQN, OCD150, OCQ180, OCQ210, OCD231, OCD241,..."
10,medical_cndition_file_MCQ_C,9666,92,"[SEQN, MCQ010, MCQ025, MCQ035, MCQ040, MCQ050,..."
11,physical_file,9359,21,"[SEQN, PAQ560, PAD590, PAD600, PAQ605, PAQ610,..."
12,Osteo_file,5935,105,"[SEQN, OSQ010A, OSQ010B, OSQ010C, OSQ020A, OSQ..."
13,Sleep_file,6546,28,"[SEQN, SLD010H, SLD020M, SLQ030, SLQ040, SLQ05..."

================================================================================
FILE: alcohol_ALQ_C
COLUMNS: 9
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ140Q', 'ALQ140U', 'ALQ150']

================================================================================
FILE: blood_pressure_cholesterol_BPQ_C
COLUMNS: 19
['SEQN', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ052', 'BPQ057', 'BPQ060', 'BPQ070', 'BPQ080', 'BPQ090A', 'BPQ090B', 'BPQ090C', 'BPQ090D', 'BPQ100A', 'BPQ100B', 'BPQ100C', 'BPQ100D']

================================================================================
FILE: diabetes_DIQ_C
COLUMNS: 36
['SEQN', 'DIQ010', 'DID040', 'DIQ220', 'DIQ160', 'DIQ170', 'DIQ180', 'DIQ190A', 'DIQ190B', 'DIQ190C', 'DIQ200A', 'DIQ200B', 'DIQ200C', 'DIQ050', 'DID060', 'DIQ060U', 'DID070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DID270', 'DIQ280', 'DIQ290', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID340', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080']

================================================================================
FILE: health_insurance_HIQ_C
COLUMNS: 17
['SEQN', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210']

================================================================================
FILE: hospital_access_HUQ_C
COLUMNS: 10
['SEQN', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ040', 'HUQ050', 'HUQ060', 'HUQ071', 'HUD080', 'HUQ090']

================================================================================
FILE: smoking_SMQ_C
COLUMNS: 37
['SEQN', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ077', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ620', 'SMD630', 'SMQ660', 'SMQ664M', 'SMQ664C', 'SMQ664W', 'SMQ664B', 'SMQ664O', 'SMQ666M', 'SMQ666C', 'SMQ666K', 'SMQ666W', 'SMQ666B', 'SMQ666S', 'SMQ666O', 'SMQ670', 'SMAQUEX2']

================================================================================
FILE: household_smokers_SMQFAM_C
COLUMNS: 5
['SEQN', 'SMD410', 'SMD415', 'SMD415A', 'SMD430']

================================================================================
FILE: weight_history_WHQ_C
COLUMNS: 58
['SEQN', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD045', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080L', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHQ270', 'WHQ280A', 'WHQ280B', 'WHQ280C', 'WHQ280D', 'WHQ280E', 'WHQ090', 'WHD100A', 'WHD100B', 'WHD100C', 'WHD100D', 'WHD100E', 'WHD100F', 'WHD100G', 'WHD100J', 'WHD100L', 'WHD100M', 'WHD100N', 'WHD100O', 'WHD100P', 'WHD100Q', 'WHD100R', 'WHD100S', 'WHQ210', 'WHD220', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150']

================================================================================
FILE: Housing_file_HOQ_C
COLUMNS: 7
['SEQN', 'HOQ040', 'HOD050', 'HOD060', 'HOQ065', 'HOQ070', 'HOQ080']

================================================================================
FILE: Occupation_file_OCQ_C
COLUMNS: 24
['SEQN', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCQ265', 'OCD270', 'OCQ290G', 'OCQ290Q', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395', 'OCQ510', 'OCQ520', 'OCQ530', 'OCQ540', 'OCQ550', 'OCQ560', 'OCQ570', 'OCQ580']

================================================================================
FILE: medical_cndition_file_MCQ_C
COLUMNS: 92
['SEQN', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051', 'MCQ053', 'MCQ080', 'MCQ092', 'MCD093', 'MCQ140', 'MCQ149', 'MCQ150G', 'MCQ150Q', 'MCQ160A', 'MCQ180A', 'MCQ190', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240B', 'MCQ240C', 'MCQ240D', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ240AA', 'MCQ240BB', 'MCQ240CC', 'MCQ240DD', 'MCQ240DK', 'MCQ245A', 'MCQ245B', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ265', 'MCQ268A', 'MCQ268B', 'MCQ268C', 'MCQ268D', 'MCQ310', 'MCQ320', 'MCD330', 'MCQ340', 'MCQ350']

================================================================================
FILE: physical_file
COLUMNS: 21
['SEQN', 'PAQ560', 'PAD590', 'PAD600', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAAQUEX']

================================================================================
FILE: Osteo_file
COLUMNS: 105
['SEQN', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030AD', 'OSQ040AD', 'OSD050AD', 'OSD030AE', 'OSQ040AE', 'OSD050AE', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD030BE', 'OSQ040BE', 'OSD030BF', 'OSQ040BF', 'OSD030BG', 'OSQ040BG', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSD050CC', 'OSD030CD', 'OSQ040CD', 'OSD050CD', 'OSD030CE', 'OSQ040CE', 'OSD050CE', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ100F', 'OSD110F', 'OSQ120F', 'OSQ090G', 'OSQ100G', 'OSD110G', 'OSQ120G', 'OSQ090H', 'OSQ100H', 'OSD110H', 'OSQ120H', 'OSQ090I', 'OSQ120I', 'OSQ090J', 'OSQ120J', 'OSQ060', 'OSQ070', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220']

================================================================================
FILE: Sleep_file
COLUMNS: 28
['SEQN', 'SLD010H', 'SLD020M', 'SLQ030', 'SLQ040', 'SLQ050', 'SLQ060', 'SLQ070A', 'SLQ070B', 'SLQ070C', 'SLQ070D', 'SLQ080', 'SLQ090', 'SLQ100', 'SLQ110', 'SLQ120', 'SLQ130', 'SLQ140', 'SLQ150', 'SLQ160', 'SLQ170', 'SLQ180', 'SLQ190', 'SLQ200', 'SLQ210', 'SLQ220', 'SLQ230', 'SLQ240']
📋 Final Columns After Merge + Rename:
['SEQN', 'ALQ101', 'ALQ110', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ140Q', 'ALQ140U', 'ALQ150', 'BPQ020', 'BPQ030', 'BPD035', 'BPQ040A', 'BPQ050A', 'BPQ052', 'BPQ057', 'BPQ060', 'BPQ070', 'BPQ080', 'BPQ090A', 'BPQ090B', 'BPQ090C', 'BPQ090D', 'BPQ100A', 'BPQ100B', 'BPQ100C', 'BPQ100D', 'DIQ010', 'DID040', 'DIQ220', 'DIQ160', 'DIQ170', 'DIQ180', 'DIQ190A', 'DIQ190B', 'DIQ190C', 'DIQ200A', 'DIQ200B', 'DIQ200C', 'DIQ050', 'DID060', 'DIQ060U', 'DID070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DID270', 'DIQ280', 'DIQ290', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID340', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'HIQ011', 'HIQ031A', 'HIQ031B', 'HIQ031C', 'HIQ031D', 'HIQ031E', 'HIQ031F', 'HIQ031G', 'HIQ031H', 'HIQ031I', 'HIQ031J', 'HIQ031AA', 'HIQ260', 'HIQ105', 'HIQ270', 'HIQ210', 'HUQ010', 'HUQ020', 'HUQ030', 'HUQ040', 'HUQ050', 'HUQ060', 'HUQ071', 'HUD080', 'HUQ090', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD055', 'SMD057', 'SMQ077', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ620', 'SMD630', 'SMQ660', 'SMQ664M', 'SMQ664C', 'SMQ664W', 'SMQ664B', 'SMQ664O', 'SMQ666M', 'SMQ666C', 'SMQ666K', 'SMQ666W', 'SMQ666B', 'SMQ666S', 'SMQ666O', 'SMQ670', 'SMAQUEX2', 'SMD410', 'SMD415', 'SMD415A', 'SMD430', 'WHD010', 'WHD020', 'WHQ030', 'WHQ040', 'WHD045', 'WHD050', 'WHQ060', 'WHQ070', 'WHD080A', 'WHD080B', 'WHD080C', 'WHD080D', 'WHD080E', 'WHD080F', 'WHD080G', 'WHD080H', 'WHD080I', 'WHD080J', 'WHD080K', 'WHD080L', 'WHD080M', 'WHD080N', 'WHD080O', 'WHD080P', 'WHD080Q', 'WHD080R', 'WHD080S', 'WHQ270', 'WHQ280A', 'WHQ280B', 'WHQ280C', 'WHQ280D', 'WHQ280E', 'WHQ090', 'WHD100A', 'WHD100B', 'WHD100C', 'WHD100D', 'WHD100E', 'WHD100F', 'WHD100G', 'WHD100J', 'WHD100L', 'WHD100M', 'WHD100N', 'WHD100O', 'WHD100P', 'WHD100Q', 'WHD100R', 'WHD100S', 'WHQ210', 'WHD220', 'WHD110', 'WHD120', 'WHD130', 'WHD140', 'WHQ150', 'HOQ040', 'HOD050', 'HOD060', 'HOQ065', 'HOQ070', 'HOQ080', 'OCD150', 'OCQ180', 'OCQ210', 'OCD231', 'OCD241', 'OCQ260', 'OCQ265', 'OCD270', 'OCQ290G', 'OCQ290Q', 'OCQ380', 'OCD390G', 'OCD391', 'OCD392', 'OCD395', 'OCQ510', 'OCQ520', 'OCQ530', 'OCQ540', 'OCQ550', 'OCQ560', 'OCQ570', 'OCQ580', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051', 'MCQ053', 'MCQ080', 'MCQ092', 'MCD093', 'MCQ140', 'MCQ149', 'MCQ150G', 'MCQ150Q', 'MCQ160A', 'MCQ180A', 'MCQ190', 'MCQ160N', 'MCQ180N', 'MCQ160B', 'MCQ180B', 'MCQ160C', 'MCQ180C', 'MCQ160D', 'MCQ180D', 'MCQ160E', 'MCQ180E', 'MCQ160F', 'MCQ180F', 'MCQ160G', 'MCQ180G', 'MCQ160M', 'MCQ170M', 'MCQ180M', 'MCQ160K', 'MCQ170K', 'MCQ180K', 'MCQ160L', 'MCQ170L', 'MCQ180L', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240B', 'MCQ240C', 'MCQ240D', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ240AA', 'MCQ240BB', 'MCQ240CC', 'MCQ240DD', 'MCQ240DK', 'MCQ245A', 'MCQ245B', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ265', 'MCQ268A', 'MCQ268B', 'MCQ268C', 'MCQ268D', 'MCQ310', 'MCQ320', 'MCD330', 'MCQ340', 'MCQ350', 'PAQ560', 'PAD590', 'PAD600', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'PAAQUEX', 'OSQ010A', 'OSQ010B', 'OSQ010C', 'OSQ020A', 'OSQ020B', 'OSQ020C', 'OSD030AA', 'OSQ040AA', 'OSD050AA', 'OSD030AB', 'OSQ040AB', 'OSD050AB', 'OSD030AC', 'OSQ040AC', 'OSD050AC', 'OSD030AD', 'OSQ040AD', 'OSD050AD', 'OSD030AE', 'OSQ040AE', 'OSD050AE', 'OSD030BA', 'OSQ040BA', 'OSD050BA', 'OSD030BB', 'OSQ040BB', 'OSD050BB', 'OSD030BC', 'OSQ040BC', 'OSD050BC', 'OSD030BD', 'OSQ040BD', 'OSD030BE', 'OSQ040BE', 'OSD030BF', 'OSQ040BF', 'OSD030BG', 'OSQ040BG', 'OSD030CA', 'OSQ040CA', 'OSD050CA', 'OSD030CB', 'OSQ040CB', 'OSD050CB', 'OSD030CC', 'OSQ040CC', 'OSD050CC', 'OSD030CD', 'OSQ040CD', 'OSD050CD', 'OSD030CE', 'OSQ040CE', 'OSD050CE', 'OSQ080', 'OSQ090A', 'OSQ100A', 'OSD110A', 'OSQ120A', 'OSQ090B', 'OSQ100B', 'OSD110B', 'OSQ120B', 'OSQ090C', 'OSQ100C', 'OSD110C', 'OSQ120C', 'OSQ090D', 'OSQ100D', 'OSD110D', 'OSQ120D', 'OSQ090E', 'OSQ100E', 'OSD110E', 'OSQ120E', 'OSQ090F', 'OSQ100F', 'OSD110F', 'OSQ120F', 'OSQ090G', 'OSQ100G', 'OSD110G', 'OSQ120G', 'OSQ090H', 'OSQ100H', 'OSD110H', 'OSQ120H', 'OSQ090I', 'OSQ120I', 'OSQ090J', 'OSQ120J', 'OSQ060', 'OSQ070', 'OSQ130', 'OSQ140Q', 'OSQ140U', 'OSQ150', 'OSQ160A', 'OSQ160B', 'OSQ170', 'OSQ180', 'OSQ190', 'OSQ200', 'OSQ210', 'OSQ220', 'SLD010H', 'SLD020M', 'SLQ030', 'SLQ040', 'SLQ050', 'SLQ060', 'SLQ070A', 'SLQ070B', 'SLQ070C', 'SLQ070D', 'SLQ080', 'SLQ090', 'SLQ100', 'SLQ110', 'SLQ120', 'SLQ130', 'SLQ140', 'SLQ150', 'SLQ160', 'SLQ170', 'SLQ180', 'SLQ190', 'SLQ200', 'SLQ210', 'SLQ220', 'SLQ230', 'SLQ240']

📊 Final Shape: (10149, 455)

,SEQN,ALQ101,ALQ110,ALQ120Q,ALQ120U,ALQ130,ALQ140Q,ALQ140U,ALQ150,BPQ020,...,SLQ150,SLQ160,SLQ170,SLQ180,SLQ190,SLQ200,SLQ210,SLQ220,SLQ230,SLQ240
0,41475,2,1,0,,,,,2,1,...,0,1,2,2,2,2,2,2,1,2
1,41476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41477,2,1,0,,,,,2,1,...,1,0,2,2,2,2,2,2,2,2
3,41478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41479,1,,3,2,5,3,2,2,2,...,0,0,2,2,2,2,2,2,2,2
5,41480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,41481,1,,3,3,4,0,,2,2,...,0,0,2,2,2,2,2,2,2,2
7,41482,1,,1,3,4,0,,1,1,...,0,3,2,2,2,2,2,1,2,2
8,41483,2,1,0,,,,,2,1,...,0,2,2,2,2,2,2,2,2,2
9,41484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,41485,2,2,,,,,,,2,...,1,0,3,2,2,2,2,2,2,3
11,41486,2,2,,,,,,,1,...,1,0,3,2,2,2,1,2,1,2
12,41487,1,,1,2,1,0,,2,1,...,0,0,2,2,2,2,2,2,2,2
13,41488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,41489,1,,3,3,5,3,3,2,2,...,0,0,2,2,2,2,2,4,2,2
15,41490,1,,1,2,2,1,3,2,2,...,0,0,2,2,2,2,2,2,1,2
16,41491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,41492,1,,2,1,1,0,,2,1,...,0,0,2,2,2,2,2,2,2,2
18,41493,2,1,3,3,1,0,,2,2,...,2,2,2,2,2,2,2,2,2,2
19,41494,1,,1,2,5,1,2,1,2,...,0,1,5,4,2,1,2,2,2,2

✅ Saved to:
C:\Users\User\Desktop\Projects\Clinical_Neighbourhood_ML_Data_Predictor\Clinical_Neighbourhood_ML_Data_Predictor\data\processed_v3\2007_2008\neighbourhood_nhanes_questionnaire_2007_2008_raw_corrected.csv