In [35]:
# =================================================================================================
# Project: NHANES Harmonized Dataset Verification
# Dataset: Demographics
# Years: 2003–2014
# Purpose: Verify Kaggle harmonized demographics data against raw NHANES DEMO files.
# Source Raw Data: CDC NHANES DEMO_C through DEMO_H XPT files
# Harmonized Data: Kaggle NHANES harmonized dataset
# Developer: Neha Khairnar
# https://www.kaggle.com/datasets/nguyenvy/nhanes-19882018
# =================================================================================================
# Step 1: Imports
# Step 2: Define file paths
# Step 3: Load raw NHANES DEMO files
# Step 4: Load Patel harmonized demographics file
# Step 5: Compare row counts by cycle
# Step 6: Compare SEQN values
# Step 7: Compare key demographic variables
# Step 8: Generate verification report
# --------------------------------------------------
import pandas as pd
from pathlib import Path

# =================================================================================================
# Step 1: Define Paths
# =================================================================================================

BASE_DIR = Path().resolve().parent
DATA_DIR = BASE_DIR / "data" / "datasets"/ "NHANE_Continuous_DemographicsData_Appended_2003_2014_Data_only"


OUTPUT_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

KAGGLE_DIR = BASE_DIR / "data" / "datasets"/ "NHANE_HARMONIZED" /"archive"
kaggle_file = KAGGLE_DIR / "demographics_clean.csv"

# =================================================================================================
# Step 2: Raw NHANES DEMO Files: 2003–2014
# =================================================================================================


# List all demographic files (update names as per your files)
demo_files = {
    "2003-2004": "DEMO_C.XPT",
    "2005-2006": "DEMO_D.XPT",
    "2007-2008": "DEMO_E.XPT",
    "2009-2010": "DEMO_F.XPT",
    "2011-2012": "DEMO_G.XPT",
    "2013-2014": "DEMO_H.XPT",
}

# =================================================================================================
# Step 3: Load Raw NHANES Demographics
# =================================================================================================

raw_list = []

for filename in demo_files.values():
    df = pd.read_sas(DATA_DIR / filename, format="xport")
    raw_list.append(df)

raw_demo = pd.concat(raw_list, ignore_index=True)

raw_demo.shape
# =================================================================================================
# Step 4: Load Patel Kaggle Harmonized Demographics
# =================================================================================================
"""
| SDDSRVYR | Cycle            |
| -------- | ---------------- |
| 1        | NHANES III       |
| 2        | NHANES 1999-2002 |
| 3        | NHANES 2003-2004 |
| 4        | NHANES 2005-2006 |
| 5        | NHANES 2007-2008 |
| 6        | NHANES 2009-2010 |
| 7        | NHANES 2011-2012 |
| 8        | NHANES 2013-2014 |
| 9        | NHANES 2015-2016 |
| 10       | NHANES 2017-2018 |
"""

    
kaggle_demo = pd.read_csv(kaggle_file)
Kaggle_demo_2003_2014 = kaggle_demo[
    kaggle_demo["SDDSRVYR"].isin([3,4,5,6,7,8])
]

kaggle_demo.shape

# =================================================================================================
# Step 5: Inspect Columns
# =================================================================================================
print("\nInspecting columns for -  raw NHANE vs harmonized kaggle NHANE :")
print("RAW NHANE columns:")
print(raw_demo.columns.tolist())
print("\nKAGGLE NHANE columns:")
print(kaggle_demo.columns.tolist())
print("-----------------------------------------------------")

print("\nInspecting Rows count for - raw NHANE vs harmonized kaggle NHANE :")
print("\nRaw NHANE rows:", len(raw_demo))
print("Kaggle NHANE total rows:", len(kaggle_demo))
print("Kaggle NHANE rows for years 2003-2014:", len(Kaggle_demo_2003_2014))
print("-----------------------------------------------------")

print("\nInspecting Missing for - raw NHANE vs harmonized kaggle NHANE :")
raw_seqn = set(raw_demo["SEQN"])
kaggle_seqn = set(Kaggle_demo_2003_2014["SEQN"])
print("Missing in Kaggle NHANE:", len(raw_seqn - kaggle_seqn))
print("Extra in Kaggle NHANE:", len(kaggle_seqn - raw_seqn))
print("-----------------------------------------------------")
# =================================================================================================
# Step 5: Validate both exist participant IDS SEQN
# =================================================================================================

# Only participants that exist in BOTH datasets
print("\nvalidation check on participants that exist in BOTH - raw NHANE vs harmonized kaggle NHANE :")
verified = raw_demo.merge(
    Kaggle_demo_2003_2014,
    on="SEQN",
    how="inner",
    suffixes=("_RAW", "_KAGGLE")
)

print("Verified participants:", len(verified))
print("-----------------------------------------------------")

# =================================================================================================
# Step 6: Compare every column
# =================================================================================================

##Steps to troubleshoot missing columns . 
## eg.MISSING IN Kaggle below columns found missing in harmonized dataset. To troublehsoot, we need to find below variables.
#There are two saperate CSV in kaggle dataset dictionary_nhanes.csv, which help to troubleshoot nelow missing columns gets harmonized into another variable.
# eg. DMDBORN -> DMDBORN4 because some csvs are using DMDBORN and some cycles are revised to DMDBORN4 or DMDBORN2 so on.
"""
AIALANG
DMDBORN
DMDBORN2
DMDHRBR2
DMDHRBRN
DMQMILIT
INDFMINC
INDHHINC
RIDAGEEX
"""

raw_demo.columns = raw_demo.columns.str.upper()
Kaggle_demo_2003_2014.columns = Kaggle_demo_2003_2014.columns.str.upper()

raw_cols = set(raw_demo.columns)
kaggle_cols = set(Kaggle_demo_2003_2014.columns)

common_cols = sorted(raw_cols.intersection(kaggle_cols))
missing_in_kaggle = sorted(raw_cols - kaggle_cols)
extra_in_kaggle = sorted(kaggle_cols - raw_cols)

print("=" * 80)
print("RAW NHANES COLUMNS:", len(raw_cols))

print("=" * 80)
print("PATEL COLUMNS:", len(kaggle_cols))

print("=" * 80)
print("COMMON COLUMNS:", len(common_cols))

print("=" * 80)
print("MISSING IN Kaggle:", len(missing_in_kaggle))

print("=" * 80)
print("EXTRA IN Kaggle:", len(extra_in_kaggle))


print("=" * 80)
print("\nCOMMON COLUMNS")
for c in common_cols:
    print(c)
print("=" * 80)

print("\nMISSING IN Kaggle")
for c in missing_in_kaggle:
    print(c)
print("=" * 80)

print("\nEXTRA IN Kaggle")
for c in extra_in_kaggle:
    print(c)

print("=" * 80)
# =================================================================================================
# Step 6: Report of which column is missing and need to investigate why
# =================================================================================================
report = pd.DataFrame({
    "column_name": sorted(raw_cols.union(patel_cols))
})

report["exists_in_raw"] = report["column_name"].isin(raw_cols)
report["exists_in_kaggle"] = report["column_name"].isin(kaggle_cols)

report["status"] = report.apply(
    lambda x: "YES"
    if x["exists_in_raw"] and x["exists_in_kaggle"]
    else "NO",
    axis=1
)

report
print("\n-----------------------------------------------------")

# =================================================================================================
# 1. Final Kaggle dataset with ONLY common columns from raw
# =================================================================================================

raw_demo.columns = raw_demo.columns.str.upper()
Kaggle_demo_2003_2014.columns = Kaggle_demo_2003_2014.columns.str.upper()

raw_cols = set(raw_demo.columns)
kaggle_cols = set(Kaggle_demo_2003_2014.columns)

common_cols = sorted(raw_cols.intersection(patel_cols))

kaggle_common_only = Kaggle_demo_2003_2014[common_cols].copy()

print("Kaggle dataset with common raw columns only:")
print(kaggle_common_only.shape)

display(kaggle_common_only.head())

print("\n-----------------------------------------------------")
# =================================================================================================
# 2. Kaggle dataset 
# =================================================================================================
print("Kaggle dataset with all columns :")
print(Kaggle_demo_2003_2014.shape)

display(Kaggle_demo_2003_2014.head())

Inspecting columns for -  raw NHANE vs harmonized kaggle NHANE :
RAW NHANE columns:
['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIDEXMON', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDAGEEX', 'RIDRETH1', 'RIDRETH2', 'DMQMILIT', 'DMDBORN', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDEDUC', 'DMDSCHOL', 'DMDMARTL', 'DMDHHSIZ', 'INDHHINC', 'INDFMINC', 'INDFMPIR', 'RIDEXPRG', 'DMDHRGND', 'DMDHRAGE', 'DMDHRBRN', 'DMDHREDU', 'DMDHRMAR', 'DMDHSEDU', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANG', 'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA', 'DMDFMSIZ', 'DMDBORN2', 'INDHHIN2', 'INDFMIN2', 'DMDHRBR2', 'RIDRETH3', 'RIDEXAGY', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC', 'DMDBORN4', 'AIALANGA', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRBR4']

KAGGLE NHANE columns:
['SEQN', 'SEQN_new', 'AIALANGA', 'DMAETHN', 'DMAETHNR', 'DMARACE', 'DMARACER', 'DMDBORN4', 'DMDCITZN', 'DMDEDUC', 'DMDEDUC2', 'DMDEDUC3', 'DMDFMSIZ', 'DMDHHSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRAGE', 'DMDHRBR4', 'DMDHREDU', 'DMDHRGND', 'DMDHRMAR', 'DMDHSEDU', 'DMDMARTL', 'DMDSCHOL', 'DMDYRSUS', 'DMPCNTYR', 'DMPCREGN', 'DMPFIPSR', 'DMPFSEQ', 'DMPMETRO', 'DMQADFC', 'DMQMILIZ', 'FIAINTRP', 'FIALANG', 'FIAPROXY', 'HAA1', 'HAA2', 'HAA2A', 'HAA3', 'HAA4', 'HAA5', 'HAA6A', 'HAA6B', 'HAA6C', 'HAA6D', 'HAD2', 'HAINTVR', 'HALANG', 'HAV10R', 'HAV11', 'HAV1S', 'HAV2S', 'HAV3S', 'HAV4S', 'HAV5', 'HAV6S', 'HAV7R', 'HAV8', 'HAV9', 'HAVERS', 'HAY10', 'HAY6', 'HAY7', 'HAY8', 'HAY9', 'HFA13', 'HFAGERR', 'HFC1', 'HFC10', 'HFC11', 'HFC7S', 'HFC8S', 'HFC9', 'HFE1', 'HFE10', 'HFE11', 'HFE12', 'HFE13', 'HFE14', 'HFE15', 'HFE16', 'HFE17', 'HFE18', 'HFE2', 'HFE3', 'HFE4', 'HFE5', 'HFE6', 'HFE7', 'HFE8A', 'HFE8B', 'HFE8C', 'HFE8D', 'HFE8E', 'HFE9', 'HFF10', 'HFF11', 'HFF12A', 'HFF12B', 'HFF13A', 'HFF13B', 'HFF13DA', 'HFF13DB', 'HFF13E', 'HFF14A', 'HFF14B', 'HFF14D', 'HFF15A', 'HFF15B', 'HFF16A', 'HFF16B', 'HFF16D', 'HFF16E', 'HFF17A', 'HFF17B', 'HFF18', 'HFF20R', 'HFF4', 'HFF5', 'HFF6A', 'HFF6B', 'HFF6C', 'HFF6D', 'HFF7', 'HFF8', 'HFF9', 'HFHEMPL', 'HFHMLSV', 'HFHSEQN', 'HFINTVR', 'HFRELR', 'HFVERS', 'HSAGEU', 'HSAITMOR', 'HSDOIMO', 'HXPSESSR', 'HXPTIDW', 'HXPTIMO', 'HYAITMO', 'INDFMIN2', 'INDFMPIR', 'INDHHIN2', 'MIAINTRP', 'MIALANG', 'MIAPROXY', 'MXPSESSR', 'MXPTIDW', 'MXPTIMO', 'RIAGENDR', 'RIDAGEMN', 'RIDAGEYR', 'RIDEXAGM', 'RIDEXAGY', 'RIDEXMON', 'RIDEXPRG', 'RIDPREG', 'RIDRETH1', 'RIDRETH2', 'RIDRETH3', 'RIDSTATR', 'SDDSRVYR', 'SDJ1REPN', 'SDMVPSU', 'SDMVSTRA', 'SDPPHASE', 'SDPPSU1', 'SDPPSU2', 'SDPSTRA1', 'SDPSTRA2', 'SIAINTRP', 'SIALANG', 'SIAPROXY', 'WTINT2YR', 'WTINT4YR', 'WTIREP01', 'WTIREP02', 'WTIREP03', 'WTIREP04', 'WTIREP05', 'WTIREP06', 'WTIREP07', 'WTIREP08', 'WTIREP09', 'WTIREP10', 'WTIREP11', 'WTIREP12', 'WTIREP13', 'WTIREP14', 'WTIREP15', 'WTIREP16', 'WTIREP17', 'WTIREP18', 'WTIREP19', 'WTIREP20', 'WTIREP21', 'WTIREP22', 'WTIREP23', 'WTIREP24', 'WTIREP25', 'WTIREP26', 'WTIREP27', 'WTIREP28', 'WTIREP29', 'WTIREP30', 'WTIREP31', 'WTIREP32', 'WTIREP33', 'WTIREP34', 'WTIREP35', 'WTIREP36', 'WTIREP37', 'WTIREP38', 'WTIREP39', 'WTIREP40', 'WTIREP41', 'WTIREP42', 'WTIREP43', 'WTIREP44', 'WTIREP45', 'WTIREP46', 'WTIREP47', 'WTIREP48', 'WTIREP49', 'WTIREP50', 'WTIREP51', 'WTIREP52', 'WTMEC2YR', 'WTMEC4YR', 'WTMREP01', 'WTMREP02', 'WTMREP03', 'WTMREP04', 'WTMREP05', 'WTMREP06', 'WTMREP07', 'WTMREP08', 'WTMREP09', 'WTMREP10', 'WTMREP11', 'WTMREP12', 'WTMREP13', 'WTMREP14', 'WTMREP15', 'WTMREP16', 'WTMREP17', 'WTMREP18', 'WTMREP19', 'WTMREP20', 'WTMREP21', 'WTMREP22', 'WTMREP23', 'WTMREP24', 'WTMREP25', 'WTMREP26', 'WTMREP27', 'WTMREP28', 'WTMREP29', 'WTMREP30', 'WTMREP31', 'WTMREP32', 'WTMREP33', 'WTMREP34', 'WTMREP35', 'WTMREP36', 'WTMREP37', 'WTMREP38', 'WTMREP39', 'WTMREP40', 'WTMREP41', 'WTMREP42', 'WTMREP43', 'WTMREP44', 'WTMREP45', 'WTMREP46', 'WTMREP47', 'WTMREP48', 'WTMREP49', 'WTMREP50', 'WTMREP51', 'WTMREP52']
-----------------------------------------------------

Inspecting Rows count for - raw NHANE vs harmonized kaggle NHANE :

Raw NHANE rows: 61087
Kaggle NHANE total rows: 135310
Kaggle NHANE rows for years 2003-2014: 61087
-----------------------------------------------------

Inspecting Missing for - raw NHANE vs harmonized kaggle NHANE :
Missing in Kaggle NHANE: 0
Extra in Kaggle NHANE: 0
-----------------------------------------------------

validation check on participants that exist in BOTH - raw NHANE vs harmonized kaggle NHANE :
Verified participants: 61087
-----------------------------------------------------
================================================================================
RAW NHANES COLUMNS: 60
================================================================================
PATEL COLUMNS: 281
================================================================================
COMMON COLUMNS: 51
================================================================================
MISSING IN Kaggle: 9
================================================================================
EXTRA IN Kaggle: 230
================================================================================

COMMON COLUMNS
AIALANGA
DMDBORN4
DMDCITZN
DMDEDUC
DMDEDUC2
DMDEDUC3
DMDFMSIZ
DMDHHSIZ
DMDHHSZA
DMDHHSZB
DMDHHSZE
DMDHRAGE
DMDHRBR4
DMDHREDU
DMDHRGND
DMDHRMAR
DMDHSEDU
DMDMARTL
DMDSCHOL
DMDYRSUS
DMQADFC
DMQMILIZ
FIAINTRP
FIALANG
FIAPROXY
INDFMIN2
INDFMPIR
INDHHIN2
MIAINTRP
MIALANG
MIAPROXY
RIAGENDR
RIDAGEMN
RIDAGEYR
RIDEXAGM
RIDEXAGY
RIDEXMON
RIDEXPRG
RIDRETH1
RIDRETH2
RIDRETH3
RIDSTATR
SDDSRVYR
SDMVPSU
SDMVSTRA
SEQN
SIAINTRP
SIALANG
SIAPROXY
WTINT2YR
WTMEC2YR
================================================================================

MISSING IN Kaggle
AIALANG
DMDBORN
DMDBORN2
DMDHRBR2
DMDHRBRN
DMQMILIT
INDFMINC
INDHHINC
RIDAGEEX
================================================================================

EXTRA IN Kaggle
DMAETHN
DMAETHNR
DMARACE
DMARACER
DMPCNTYR
DMPCREGN
DMPFIPSR
DMPFSEQ
DMPMETRO
HAA1
HAA2
HAA2A
HAA3
HAA4
HAA5
HAA6A
HAA6B
HAA6C
HAA6D
HAD2
HAINTVR
HALANG
HAV10R
HAV11
HAV1S
HAV2S
HAV3S
HAV4S
HAV5
HAV6S
HAV7R
HAV8
HAV9
HAVERS
HAY10
HAY6
HAY7
HAY8
HAY9
HFA13
HFAGERR
HFC1
HFC10
HFC11
HFC7S
HFC8S
HFC9
HFE1
HFE10
HFE11
HFE12
HFE13
HFE14
HFE15
HFE16
HFE17
HFE18
HFE2
HFE3
HFE4
HFE5
HFE6
HFE7
HFE8A
HFE8B
HFE8C
HFE8D
HFE8E
HFE9
HFF10
HFF11
HFF12A
HFF12B
HFF13A
HFF13B
HFF13DA
HFF13DB
HFF13E
HFF14A
HFF14B
HFF14D
HFF15A
HFF15B
HFF16A
HFF16B
HFF16D
HFF16E
HFF17A
HFF17B
HFF18
HFF20R
HFF4
HFF5
HFF6A
HFF6B
HFF6C
HFF6D
HFF7
HFF8
HFF9
HFHEMPL
HFHMLSV
HFHSEQN
HFINTVR
HFRELR
HFVERS
HSAGEU
HSAITMOR
HSDOIMO
HXPSESSR
HXPTIDW
HXPTIMO
HYAITMO
MXPSESSR
MXPTIDW
MXPTIMO
RIDPREG
SDJ1REPN
SDPPHASE
SDPPSU1
SDPPSU2
SDPSTRA1
SDPSTRA2
SEQN_NEW
WTINT4YR
WTIREP01
WTIREP02
WTIREP03
WTIREP04
WTIREP05
WTIREP06
WTIREP07
WTIREP08
WTIREP09
WTIREP10
WTIREP11
WTIREP12
WTIREP13
WTIREP14
WTIREP15
WTIREP16
WTIREP17
WTIREP18
WTIREP19
WTIREP20
WTIREP21
WTIREP22
WTIREP23
WTIREP24
WTIREP25
WTIREP26
WTIREP27
WTIREP28
WTIREP29
WTIREP30
WTIREP31
WTIREP32
WTIREP33
WTIREP34
WTIREP35
WTIREP36
WTIREP37
WTIREP38
WTIREP39
WTIREP40
WTIREP41
WTIREP42
WTIREP43
WTIREP44
WTIREP45
WTIREP46
WTIREP47
WTIREP48
WTIREP49
WTIREP50
WTIREP51
WTIREP52
WTMEC4YR
WTMREP01
WTMREP02
WTMREP03
WTMREP04
WTMREP05
WTMREP06
WTMREP07
WTMREP08
WTMREP09
WTMREP10
WTMREP11
WTMREP12
WTMREP13
WTMREP14
WTMREP15
WTMREP16
WTMREP17
WTMREP18
WTMREP19
WTMREP20
WTMREP21
WTMREP22
WTMREP23
WTMREP24
WTMREP25
WTMREP26
WTMREP27
WTMREP28
WTMREP29
WTMREP30
WTMREP31
WTMREP32
WTMREP33
WTMREP34
WTMREP35
WTMREP36
WTMREP37
WTMREP38
WTMREP39
WTMREP40
WTMREP41
WTMREP42
WTMREP43
WTMREP44
WTMREP45
WTMREP46
WTMREP47
WTMREP48
WTMREP49
WTMREP50
WTMREP51
WTMREP52
================================================================================

-----------------------------------------------------
Kaggle dataset with common raw columns only:
(61087, 51)

,AIALANGA,DMDBORN4,DMDCITZN,DMDEDUC,DMDEDUC2,DMDEDUC3,DMDFMSIZ,DMDHHSIZ,DMDHHSZA,DMDHHSZB,...,RIDSTATR,SDDSRVYR,SDMVPSU,SDMVSTRA,SEQN,SIAINTRP,SIALANG,SIAPROXY,WTINT2YR,WTMEC2YR
54998,1.0,1.0,1.0,1.0,NaN,11.0,NaN,2,NaN,NaN,...,2,3,2,39,21005,2.0,1.0,2.0,5512.320949,5824.782465
54999,1.0,1.0,1.0,1.0,NaN,11.0,NaN,6,NaN,NaN,...,2,3,1,41,21006,2.0,1.0,2.0,5422.140453,5564.039715
55000,1.0,1.0,1.0,1.0,NaN,8.0,NaN,5,NaN,NaN,...,2,3,2,35,21007,2.0,1.0,1.0,39764.177412,40591.066325
55001,1.0,1.0,1.0,1.0,NaN,10.0,NaN,7,NaN,NaN,...,2,3,1,32,21008,2.0,1.0,2.0,5599.499351,5696.750596
55002,1.0,1.0,1.0,2.0,3.0,NaN,NaN,2,NaN,NaN,...,2,3,2,31,21009,2.0,1.0,2.0,97593.678977,97731.727244

-----------------------------------------------------
Kaggle dataset with all columns :
(61087, 281)

,SEQN,SEQN_NEW,AIALANGA,DMAETHN,DMAETHNR,DMARACE,DMARACER,DMDBORN4,DMDCITZN,DMDEDUC,...,WTMREP43,WTMREP44,WTMREP45,WTMREP46,WTMREP47,WTMREP48,WTMREP49,WTMREP50,WTMREP51,WTMREP52
54998,21005,C-21005,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54999,21006,C-21006,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55000,21007,C-21007,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55001,21008,C-21008,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55002,21009,C-21009,1.0,NaN,NaN,NaN,NaN,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN